### ISSUE TITLE
Wallet State

### ISSUE THREAD

**Issue by gedanziger** [bitcoingreen/bitg-webwallet#10]
Add redux state to the wallet, and keep these params accessible:

- `address` - `string`
- `privateKey` - `string`
- `balance` - `number`
- `utxo` - `[txid: string, amount:number]`

On create a wallet, or unlock the wallet, the address and private key should be initialized. For mock data purposes, initialize address to `GTsqojGaG2sy4uUTwyqwjxDtaVaF9ja5DV` (until the bitg-js lib is completed).

**Comment by 0xweb3builder** [comment]
Closed by 666b11a9446e17c5764a5773bf1dc087d51220cc
