### ISSUE TITLE
Get UTXOs from API

### ISSUE THREAD

**Issue by gedanziger** [bitcoingreen/bitg-webwallet#12]
After login, have a service call get the balance of the initialized address from this api call:

https://www.coinexplorer.net/api/v1/BITG/address/unspent?address=Gabc

until bitg-js lib is implemented, use this param for the address above: GTsqojGaG2sy4uUTwyqwjxDtaVaF9ja5DV. It should be pulled from the application state set in #10.

Set the amount, id from the UTXOs in the response to the application state.

**Comment by 0xweb3builder** [comment]
completed by 699cfc54dd672c4f9afbc0120a43e7cb049a48c1
