### ISSUE TITLE
Text cutoff at edge of address text field (desktop res)

### ISSUE THREAD

**Issue by gedanziger** [bitcoingreen/bitg-webwallet#18]
In chrome on OSX at 1920x1080, the edge of the bitg address is cut off by the "Copy Address" button. 

Update text fields to avoid getting this cutoff.

![screen shot 2018-12-03 at 2 53 48 pm](https://user-images.githubusercontent.com/5342263/49406790-6a9a5400-f70b-11e8-94b7-d32125d4689c.png)

**Comment by 0xweb3builder** [comment]
fixed by 666b11a9446e17c5764a5773bf1dc087d51220cc
