### ISSUE TITLE
add encrypt/decrypt feature

### ISSUE THREAD

**Issue by 0xweb3builder** [bitcoingreen/bitg-webwallet#23]
- add encrypt/decrypt function
- add keystore export function
- add import keystore function

This issue should implement unlock_wallet, save_wallet screens.

**Comment by 0xweb3builder** [comment]
Import address https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/addresses.js#L40

**Comment by gedanziger** [comment]
For keystores, use the standard keystore lib found here: https://github.com/ethereumjs/keythereum

It implements a keystore standard, given an initialization vector (`iv` in code). IV params should be kept to config.

**Comment by 0xweb3builder** [comment]
verified by ea75dd78bba00ff59e0cfc54b1abe8e37b7a9277

**Comment by 0xweb3builder** [comment]
`importAddressFromWif` was updated to `importAddressFromPrivateKey` by 82fded0fa33023c06d26f5125bbb156b0ac91538
