### ISSUE TITLE
Compute transaction from UTXOs

### ISSUE THREAD

**Issue by gedanziger** [bitcoingreen/bitg-webwallet#24]
Compute a transaction from UTXOs not using a change address. Compute a transaction according the following process:

1. Check if the amount is less than the total balance. If amount is greater, stop process and show user error ("Insufficient Funds").
2. Set transactionUtxos = [], transactionUtxoValue = 0, transactionValue = amount user is trying to send.
3. Add top UTXO to transactionUtxos. Add value of transactionUtxoValue = utxo.value.
4. Check if transactionUtxoValue >= value of transaction. If yes, proceed. Otherwise, repeat step 3 with next of utxos list.

**Comment by 0xweb3builder** [comment]
Create a transaction https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/transactions.js#L63

**Comment by 0xweb3builder** [comment]
@kdbusiness121 
coinexplorer api has call limit?

**Comment by 0xweb3builder** [comment]
@gedanziger 
utxos should be fetched when mounting page?
or utxos should be fetched just before submit sending tx?

**Comment by 0xweb3builder** [comment]
Verified by 3de96f7b0bd5e2747305a24b1b3c23b02cb94050
