### ISSUE TITLE
Set transaction inputs, outputs from UTXOs

### ISSUE THREAD

**Issue by gedanziger** [bitcoingreen/bitg-webwallet#25]
Set transaction inputs as each of the UTXOs from step #24. 

For each utxo `i` in the array transactionUtxos:

Follow this pseudocode:
```
const rawTransaction= new bitcoin.TransactionBuilder()
for (i = 0 : transactionUtxos.length):
  rawTransaction.addInput(transactionUtxos[i].txId, transactionUtxos[i].vout)
```

This generates the inputs. For the outputs, do the following:

Compute these amounts:
- `amount` - this is the transaction amount sent from the input field
- `change` - this is the change remaining. It is calculated by the sum of the the utxo amounts used in the transaction (`transactionUtxos`) - (`amount` + `fee`).
- `fee` - this amount is fixed to a constant `FEE_AMOUNT` that we define in the app

Represent all amounts in satoshi.

```
rawTransaction.addOutput('RECEIVE_ADDRESS', `amount`)
rawTransaction.addOutput('MY_ADDRESS', `change`)
```

Set the receive address to the one entered in the input field, and my address to the users own address.

**Comment by 0xweb3builder** [comment]
@gedanziger 
Can you post details about FEE?

**Comment by 0xweb3builder** [comment]
minor FEE and fixed fee will be used for all transactions?

**Comment by 0xweb3builder** [comment]
Verified by 0a98add0fa383daba235485af4cc78cfdb813cfd
