### ISSUE TITLE
Main Wallet -- Send Screen

### ISSUE THREAD

**Issue by gedanziger** [bitcoingreen/bitg-webwallet#9]
Implement the send screen (second tab of the main wallet).

[Desktop Version](https://sketch.cloud/s/1x7vn/eKav4mz)

[Mobile Version](https://sketch.cloud/s/1x7vn/zx8LZgl)

**Comment by 0xweb3builder** [comment]
Verified fixed in 8e3f1887ee46bd5f0652b5a746c154e3166efdfa
